### ISSUE TITLE
TODO général 3.0

### ISSUE THREAD

**Issue by ykonoclast** [ykonoclast/FadingsUP#34]
- [ ] Errata pour UP général sur lettres de changes : discount (cf. p189+190 du companion).

- [ ] Rangs militaires : prendre en compte notes manuscripte (lt min pour statut, ss off sinon) et mettre un av pour acheter des rangs de plus (Il leur est possible de payer le coût (non modifié! on ne multiplie pas par deux) de la p111 de LotE pour avoir plus., mettre direct dans FU, pas de renvoi) cf. p115 de legions of the empire

- [ ] Fric : renvoi à UP + stipende si pas usufruit

- [ ] fiefs : opulence en fonction lieu

- [ ] Mode : utiliser UP

- [ ] refaire totalement règles qualité et rareté (renvoi UP + extraits Polairs?)

- [ ] Orga secrètes (oeil, convent) : utiliser appartenance

- [ ] shields : leakage etc., lenteur calculéé est action inhab

- [ ] Refaire règle et ajouter elt fad (guérison)

- [ ] Augure : Mieux découper les pouvoirs, placer notamment la partie "futur" du pouvoir de rang 3 dans le pouvoir de rang 5

- [ ] Durée psi : Temporaire = 1 tour glissant
Etendue : # tours glissants = arcane
Prolongee : # tours glissants = 2 × arcane

- [ ] lien sympathique : 1 scene de méditation pour activer lien. Sinon cheaté.

- [ ] L'illustration du haut de page est toute pixellisée alors que celle du bas de page est correcte.
Profiter d'une refonte totale de la mise ne page pour régler ce problème (dessins juste sur le bord extérieur, un truc permettant de réduire la marge intérieure de l'autre côté).

- [ ] avatanges : sauf conduit pour psion protégé par une famille noble

- [ ] règles de vaisseaux

- [ ] companion

- [ ] PotCS

- [ ] tDBtS

- [ ] LotKW

- [ ] MotJW

- [ ] Byz2

- [ ] LotKW

- [ ] fiche :
- [ ] Ajouter séquelle
- [ ]  Améliorer le tableau des armes pour indiauer le type de dégâts, le malus pour toucher et autres points des notes (ainsi qu'autre aspect jugé nécessaire)
- [ ]  Taille et lisibilité des polices : peut être passer à une police plus claire pour les petits titres
- [ ]  Arts physiques devient action, vérifier ordre alphabétique
